Repository TycheSoftwares/woocommerce-delivery-notes, pull requests merged in 2024-03, with the labels that each got.

#302 Fixed HPOS Compatibility
  woocommerce-delivery-notes.php
Labels: type: bug

#306 Fix-#239
  assets/css/admin.css
Labels: type: enhancement, type: ui/ux

#304 Fixed Showing warning on the print invoices.
  includes/wcdn-template-functions.php
Labels: type: bug

#310 Fixed some warnings on template settings page.
  includes/admin/views/wcdn-comman-field.php
Labels: type: bug

#317 Fixed Selected order status in attach email setting of the template is not set empty.
  includes/admin/views/wcdn-customization.php
  includes/class-woocommerce-delivery-notes.php
Labels: type: bug

#319 Fixed Payment Received stamp is not working in receipt templates setting
  templates/print-order/simple/receipt/print-content.php
  templates/print-order/simple/style.css
Labels: type: bug

#326 Fixed Disable all the field when the default template is selected.
  assets/js/admin.js
Labels: type: enhancement

#325 Fixed Showing warrnings on Invoice Settings page.
  includes/admin/views/wcdn-customization.php
Labels: type: bug

#324 Fixed Payment Received stamp is not working in receipt templates settings
  templates/print-order/simple/style.css
Labels: type: bug
